set(CMAKE_POSITION_INDEPENDENT_CODE ON  CACHE BOOL     "Enable position independent code")
set(BUILD_SHARED_LIBS               OFF CACHE BOOL     "Build static libraries by default")
set(BUILD_STATIC_LIBS               ON  CACHE BOOL     "Build static libraries by default")

set(BUILD_TESTS                     OFF CACHE BOOL     "Disable building tests")
set(BUILD_EXAMPLES                  OFF CACHE BOOL     "Disable building examples")
set(CMAKE_CXX_STANDARD_REQUIRED     ON  CACHE BOOL     "Enforce C++ standard")
set(CMAKE_C_STANDARD_REQUIRED       ON  CACHE BOOL     "Enforce C standard")
set(USE_INTERNAL_FPCONV             ON  CACHE BOOL     "Use internal strtod() / g_fmt() code for performance")
set(NGHTTP2_STATICLIB               ON  CACHE BOOL     "Use static nghttp2 library")
set(BUILD_CURL_EXE                  OFF CACHE BOOL     "" FORCE)
set(CURL_USE_LIBSSH2                OFF CACHE BOOL     "" FORCE)
set(CURL_STATICLIB                  ON  CACHE BOOL     "Build curl as static library")
set(CURL_USE_SECTRANSP              OFF CACHE BOOL     "Disable SecureTransport")
set(CURL_USE_MBEDTLS                OFF CACHE BOOL     "Disable mbedTLS")
set(CURL_USE_WOLFSSL                OFF CACHE BOOL     "Disable wolfSSL")
set(CURL_USE_BEARSSL                OFF CACHE BOOL     "Disable BearSSL")
set(CURL_DISABLE_INSTALL            ON  CACHE BOOL     "Disable curl install")
set(CURL_DISABLE_LDAP               ON  CACHE BOOL     "Disable LDAP")
set(CURL_DISABLE_LDAPS              ON  CACHE BOOL     "Disable LDAPS")
set(CURL_DISABLE_RTSP               ON  CACHE BOOL     "Disable RTSP")
set(CURL_DISABLE_PROXY              OFF CACHE BOOL     "Disable proxy support")
set(CURL_DISABLE_DICT               ON  CACHE BOOL     "Disable DICT")
set(CURL_DISABLE_TELNET             ON  CACHE BOOL     "Disable TELNET")
set(CURL_DISABLE_TFTP               ON  CACHE BOOL     "Disable TFTP")
set(CURL_DISABLE_POP3               ON  CACHE BOOL     "Disable POP3")
set(CURL_DISABLE_IMAP               ON  CACHE BOOL     "Disable IMAP")
set(CURL_DISABLE_SMTP               ON  CACHE BOOL     "Disable SMTP")
set(CURL_DISABLE_GOPHER             ON  CACHE BOOL     "Disable Gopher")
set(CURL_USE_LIBPSL 		        OFF CACHE BOOL     "Disable libpsl")
set(FMT_HEADER_ONLY                 ON  CACHE BOOL     "Use fmt as header-only library")
set(FMT_DOC                         OFF CACHE BOOL     "Disable building documentation in fmt")
set(FMT_TEST                        OFF CACHE BOOL     "Disable building tests in fmt")
set(FMT_INSTALL                     ON  CACHE BOOL     "Enable installation of fmt")
set(MULTIPLE_THREADS 		        OFF CACHE BOOL     "Disable multithreading support in lua cjson")
set(MZ_BZIP2                        OFF CACHE BOOL     "Disable bzip2 support in minizip-ng")
set(MZ_FETCH_LIBS                   OFF CACHE BOOL     "Disable fetching third-party libs in minizip-ng")
set(MZ_ZLIB                         ON  CACHE BOOL     "Enable zlib support in minizip-ng")
set(MZ_ICONV                        OFF CACHE BOOL     "Disable iconv in minizip-ng")
set(ZLIB_COMPAT                     ON  CACHE BOOL     "Enable zlib compatibility mode in zlib-ng")
set(ZLIB_ALIASES                    ON  CACHE BOOL     "Enable zlib alias symbols in zlib-ng")
set(ZLIB_ENABLE_TESTS               OFF CACHE BOOL     "Disable building tests in zlib-ng")
set(ZLIBNG_ENABLE_TESTS 	        OFF CACHE BOOL     "Disable building tests in zlib-ng")

if(WIN32)
    set(CURL_USE_SCHANNEL           ON  CACHE INTERNAL "" FORCE)
    set(CURL_WINDOWS_SSPI           ON  CACHE INTERNAL "" FORCE)
    set(CURL_USE_OPENSSL            OFF CACHE BOOL     "Use OpenSSL for TLS/SSL" FORCE)
else()
    set(CURL_USE_OPENSSL            ON  CACHE BOOL     "Use OpenSSL for TLS/SSL" FORCE)
    set(CURL_USE_SCHANNEL           OFF CACHE INTERNAL "" FORCE)
    set(CURL_WINDOWS_SSPI           OFF CACHE INTERNAL "" FORCE)
endif()


# Patch the minimum cmake version in a "submodule".
# Mingw decided they would force the new version of cmake which completely breaks older deps
# Only fix is a shim or fixing it up stream :shrug:

function(millennium_process_package input_path)
    if(EXISTS "${input_path}/CMakeLists.txt")
        file(READ "${input_path}/CMakeLists.txt" CMAKELISTS_CONTENTS)
        string(REGEX REPLACE "cmake_minimum_required[ \t]*\\([ \t]*VERSION[^)]*\\)" "cmake_minimum_required(VERSION 3.21)" CMAKELISTS_CONTENTS "${CMAKELISTS_CONTENTS}")
        file(WRITE "${input_path}/CMakeLists.txt" "${CMAKELISTS_CONTENTS}")
    else()
        message(WARNING "Could not find ${input_path} to patch.")
    endif()
endfunction()

message(STATUS "[Millennium] Fetching dependencies...")

if(DISTRO_NIX)
    set(FETCHCONTENT_FULLY_DISCONNECTED ON)

    FetchContent_Declare(zlib           SOURCE_DIR "${MILLENNIUM_BASE}/deps/zlib"                                 )
    FetchContent_Declare(luajit         SOURCE_DIR "${MILLENNIUM_BASE}/deps/luajit"         SOURCE_SUBDIR fakedir )
    FetchContent_Declare(lua_cjson      SOURCE_DIR "${MILLENNIUM_BASE}/deps/luajson"        SOURCE_SUBDIR fakedir )
    FetchContent_Declare(websocketpp    SOURCE_DIR "${MILLENNIUM_BASE}/deps/websocketpp"    SOURCE_SUBDIR fakedir )
    FetchContent_Declare(fmt            SOURCE_DIR "${MILLENNIUM_BASE}/deps/fmt"            SOURCE_SUBDIR fakedir )
    FetchContent_Declare(nlohmann_json  SOURCE_DIR "${MILLENNIUM_BASE}/deps/json"           SOURCE_SUBDIR fakedir )
    FetchContent_Declare(minizip_ng     SOURCE_DIR "${MILLENNIUM_BASE}/deps/minizip"        SOURCE_SUBDIR fakedir )
    FetchContent_Declare(curl           SOURCE_DIR "${MILLENNIUM_BASE}/deps/curl"           SOURCE_SUBDIR fakedir )
    FetchContent_Declare(incbin         SOURCE_DIR "${MILLENNIUM_BASE}/deps/incbin"         SOURCE_SUBDIR fakedir )
    FetchContent_Declare(asio           SOURCE_DIR "${MILLENNIUM_BASE}/deps/asio"           SOURCE_SUBDIR fakedir )
else()
    set(THIRDPARTY_DIR "${MILLENNIUM_BASE}/thirdparty")
    FetchContent_Declare(zlib          URL "file://${THIRDPARTY_DIR}/zlib-2.2.5.tar.gz"           DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_Declare(luajit        URL "file://${THIRDPARTY_DIR}/luajit-89550023.tar.gz"        DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
    FetchContent_Declare(lua_cjson     URL "file://${THIRDPARTY_DIR}/lua_cjson-0c1fabf0.tar.gz"    DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
    FetchContent_Declare(websocketpp   URL "file://${THIRDPARTY_DIR}/websocketpp-0.8.2.tar.gz"     DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
    FetchContent_Declare(fmt           URL "file://${THIRDPARTY_DIR}/fmt-12.0.0.tar.gz"            DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
    FetchContent_Declare(nlohmann_json URL "file://${THIRDPARTY_DIR}/nlohmann_json-v3.12.0.tar.gz" DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
    FetchContent_Declare(minizip_ng    URL "file://${THIRDPARTY_DIR}/minizip_ng-4.0.10.tar.gz"     DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
    FetchContent_Declare(curl          URL "file://${THIRDPARTY_DIR}/curl-8_13_0.tar.gz"           DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
    FetchContent_Declare(incbin        URL "file://${THIRDPARTY_DIR}/incbin-22061f51.tar.gz"        DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
    FetchContent_Declare(asio          URL "file://${THIRDPARTY_DIR}/asio-1-30-0.tar.gz"           DOWNLOAD_EXTRACT_TIMESTAMP TRUE SOURCE_SUBDIR fakedir)
endif()

set(DEPENDENCIES zlib luajit incbin websocketpp fmt nlohmann_json minizip_ng lua_cjson curl asio)


foreach(dep ${DEPENDENCIES})
    string(TIMESTAMP start_time "%s")
    FetchContent_MakeAvailable(${dep})
    string(TIMESTAMP end_time "%s")
    math(EXPR duration "${end_time} - ${start_time}")
    message(STATUS "[Millennium] ${dep} completed in ${duration} seconds")
endforeach()

set(LUA_INCLUDE_DIR  luajit::header)
set(LUA_INCLUDE_DIRS luajit::header)
set(LUA_LIBRARY      luajit::lib   )
set(LUA_LIBRARIES    luajit::lib   )

include_directories(SYSTEM
    "${minizip_ng_SOURCE_DIR}"
    "${incbin_SOURCE_DIR}"
    "${asio_SOURCE_DIR}/asio/include"
    "${luajit_BINARY_DIR}"
    "${luajit_SOURCE_DIR}/src"
    "${CMAKE_SOURCE_DIR}/../hhx64/include"
)

millennium_process_package("${luajit_SOURCE_DIR}")
millennium_process_package("${curl_SOURCE_DIR}")
millennium_process_package("${websocketpp_SOURCE_DIR}")
millennium_process_package("${fmt_SOURCE_DIR}")
millennium_process_package("${nlohmann_json_SOURCE_DIR}")
millennium_process_package("${minizip_ng_SOURCE_DIR}")
millennium_process_package("${lua_cjson_SOURCE_DIR}")


set(ZLIB_ROOT "${zlib_BINARY_DIR}")
set(ZLIB_FOUND TRUE)
if(WIN32)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(ZLIB_LIBRARY "${zlib_BINARY_DIR}/zlibstaticd${CMAKE_STATIC_LIBRARY_SUFFIX}")
    else()
        set(ZLIB_LIBRARY "${zlib_BINARY_DIR}/zlibstatic${CMAKE_STATIC_LIBRARY_SUFFIX}")
    endif()
elseif(UNIX)
    set(ZLIB_LIBRARY "${zlib_BINARY_DIR}/libz${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()

set(ZLIB_LIBRARIES "${ZLIB_LIBRARY}")
set(ZLIB_INCLUDE_DIRS "${zlib_SOURCE_DIR};${zlib_BINARY_DIR}")
set(ZLIB_INCLUDE_DIR "${zlib_SOURCE_DIR};${zlib_BINARY_DIR}")

# Suppress warnings from third-party dependencies
set(_saved_c_flags   "${CMAKE_C_FLAGS}")
set(_saved_cxx_flags "${CMAKE_CXX_FLAGS}")
string(APPEND CMAKE_C_FLAGS   " -w")
string(APPEND CMAKE_CXX_FLAGS " -w")

add_subdirectory("${luajit_SOURCE_DIR}"        "${luajit_BINARY_DIR}"       )
add_subdirectory("${curl_SOURCE_DIR}"          "${curl_BINARY_DIR}"         )
add_subdirectory("${websocketpp_SOURCE_DIR}"   "${websocketpp_BINARY_DIR}"  )
add_subdirectory("${fmt_SOURCE_DIR}"           "${fmt_BINARY_DIR}"          )
add_subdirectory("${nlohmann_json_SOURCE_DIR}" "${nlohmann_json_BINARY_DIR}")
add_subdirectory("${minizip_ng_SOURCE_DIR}"    "${minizip_ng_BINARY_DIR}"   )
add_subdirectory("${lua_cjson_SOURCE_DIR}"     "${lua_cjson_BINARY_DIR}"    )

set(CMAKE_C_FLAGS   "${_saved_c_flags}")
set(CMAKE_CXX_FLAGS "${_saved_cxx_flags}")

add_dependencies(cjson luajit::lib luajit::header)
add_dependencies(luajit zlib)
add_dependencies(minizip zlib)
