file(STRINGS "${CMAKE_SOURCE_DIR}/../version" VERSION_LINES LIMIT_COUNT 2)
list(GET VERSION_LINES 1 MILLENNIUM_VERSION)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/../version")
configure_file(${CMAKE_SOURCE_DIR}/include/millennium/version.h.in ${CMAKE_BINARY_DIR}/version.h)
execute_process(COMMAND git rev-parse HEAD WORKING_DIRECTORY ${CMAKE_SOURCE_DIR} OUTPUT_VARIABLE GIT_COMMIT_HASH OUTPUT_STRIP_TRAILING_WHITESPACE)

message(STATUS "[Millennium] Version: ${MILLENNIUM_VERSION}")
message(STATUS "[Millennium] Git commit hash: ${GIT_COMMIT_HASH}")
add_compile_definitions(GIT_COMMIT_HASH="${GIT_COMMIT_HASH}" MILLENNIUM_ROOT="${CMAKE_SOURCE_DIR}" MILLENNIUM_VERSION="${MILLENNIUM_VERSION}")
