set(CMAKE_C_COMPILER "${MSVC_BASE_PATH}/bin/Hostx64/x86/cl.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${MSVC_BASE_PATH}/bin/Hostx64/x86/cl.exe" CACHE FILEPATH "" FORCE)

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(MSVC_TOOLSET_VERSION "${MSVC_TOOLSET_VERSION}")
set(MSVC_BASE "${MSVC_BASE_PATH}")
set(WIN_SDK "C:/Program Files (x86)/Windows Kits/10")
set(WIN_SDK_VERSION "${MSVC_SDK_VERSION}")

set(CMAKE_LIBRARY_ARCHITECTURE x86)
set(CMAKE_EXE_LINKER_FLAGS "/LIBPATH:\"${MSVC_BASE_PATH}/lib/x86\" /LIBPATH:\"${WIN_SDK}/Lib/${WIN_SDK_VERSION}/ucrt/x86\" /LIBPATH:\"${WIN_SDK}/Lib/${WIN_SDK_VERSION}/um/x86\"" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "" FORCE)
