import { findClassModule } from '../class-mapper';

type QuickAccessMenuClasses = Record<
	| 'ActiveTab'
	| 'AllTabContents'
	| 'BackgroundAnimation'
	| 'BatteryDetailsLabels'
	| 'BatteryIcon'
	| 'BatteryPercentageLabel'
	| 'BatteryProjectedLabel'
	| 'BatteryProjectedValue'
	| 'BatterySectionContainer'
	| 'Blocked'
	| 'ComingSoon'
	| 'Container'
	| 'ContentTransition'
	| 'Down'
	| 'EmptyNotifications'
	| 'Enter'
	| 'EnterActive'
	| 'Exit'
	| 'ExitActive'
	| 'FooterBoxShadow'
	| 'FriendsListTabPanel'
	| 'FriendsTitle'
	| 'FullHeight'
	| 'HeaderAndFooterVisible'
	| 'HeaderContainer'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'KeyboardButton'
	| 'Label'
	| 'LowBattery'
	| 'LowBatteryGauge'
	| 'Menu'
	| 'Open'
	| 'PanelExitAnchor'
	| 'PanelOuterNav'
	| 'PanelSection'
	| 'PanelSectionRow'
	| 'PanelSectionTitle'
	| 'PopupBody'
	| 'QuickAccessMenu'
	| 'QuickAccessNotifications'
	| 'ReallyLow'
	| 'Remaining'
	| 'Selected'
	| 'Tab'
	| 'TabContentColumn'
	| 'TabGroupPanel'
	| 'TabPanelHidden'
	| 'Tabs'
	| 'TabsWithFooter'
	| 'Text'
	| 'Title'
	| 'TransitionMenuDelay'
	| 'Up'
	| 'VR'
	| 'ViewPlaceholder'
	| 'VoiceTab'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hoverAnimation'
	| 'vrgamepadui-floating-bar-popup-panel-height'
	| 'vrgamepadui-floating-bar-popup-panel-width'
	| 'vrgamepadui-floating-keyboard-height'
	| 'vrgamepadui-floating-keyboard-width'
	| 'vrgamepadui-floating-side-panel-height'
	| 'vrgamepadui-floating-side-panel-width',
	string
>;

type ScrollPanelClasses = Record<'ScrollBoth' | 'ScrollPanel' | 'ScrollX' | 'ScrollY', string>;

type GamepadDialogClasses = Record<
	| 'ActiveAndUnfocused'
	| 'AlignCenter'
	| 'AlignLeft'
	| 'AlignRight'
	| 'BackgroundAnimation'
	| 'BasicTextInput'
	| 'BeforeChildren'
	| 'BottomButtons'
	| 'Button'
	| 'ChildrenWidthFixed'
	| 'ChildrenWidthGrow'
	| 'Clickable'
	| 'CompactPadding'
	| 'ControlsListChild'
	| 'ControlsListOuterPanel'
	| 'Disabled'
	| 'DropDownControlButtonContents'
	| 'DropDownRow'
	| 'ExtraPaddingOnChildrenBelow'
	| 'ExtraSpacing'
	| 'Field'
	| 'FieldChildrenInner'
	| 'FieldChildrenWithIcon'
	| 'FieldClickTarget'
	| 'FieldDescription'
	| 'FieldIcon'
	| 'FieldLabel'
	| 'FieldLabelRow'
	| 'FieldLabelValue'
	| 'Front'
	| 'FullWidth'
	| 'GamepadDialogContent'
	| 'GamepadDialogContent_InnerWidth'
	| 'HighlightOnFocus'
	| 'IconContainer'
	| 'InlineWrapShiftsChildrenBelow'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'ItemMaxSizeDesktop'
	| 'Label'
	| 'LabelFieldValue'
	| 'ModalClickToDismiss'
	| 'ModalPosition'
	| 'NoHeaderPadding'
	| 'NoMinWidth'
	| 'On'
	| 'QuickAccess-Menu'
	| 'ScrollWithin'
	| 'Spacer'
	| 'StandaloneFieldSeparator'
	| 'StandardPadding'
	| 'StandardSpacing'
	| 'Toggle'
	| 'ToggleRail'
	| 'ToggleSwitch'
	| 'VR'
	| 'VerticalAlignCenter'
	| 'WithBottomSeparator'
	| 'WithBottomSeparatorStandard'
	| 'WithBottomSeparatorThick'
	| 'WithChildrenBelow'
	| 'WithDescription'
	| 'WithFirstRow'
	| 'WithStandardPadding'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hoverAnimation'
	| 'slideInAnimation',
	string
>;

type QuickAccessControlsClasses = Record<
	| 'BackgroundAnimation'
	| 'BatteryDetailsLabels'
	| 'BatteryIcon'
	| 'BatteryPercentageLabel'
	| 'BatteryProjectedLabel'
	| 'BatteryProjectedValue'
	| 'BatterySectionContainer'
	| 'ComingSoon'
	| 'EmptyNotifications'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'Label'
	| 'LowBattery'
	| 'LowBatteryGauge'
	| 'PanelSection'
	| 'PanelSectionRow'
	| 'PanelSectionTitle'
	| 'QuickAccessNotifications'
	| 'ReallyLow'
	| 'Remaining'
	| 'Text'
	| 'VR'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hoverAnimation',
	string
>;

type UpdaterFieldClasses = Record<
	| 'ApplyingText'
	| 'BackgroundAnimation'
	| 'BatteryLowWarning'
	| 'Body'
	| 'CurrentStatus'
	| 'Denominator'
	| 'EventDetailTitle'
	| 'EventDetailsBody'
	| 'EventDetailsSubTitle'
	| 'InsufficientBatteryText'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'Label'
	| 'Numerator'
	| 'OOBEUpdateStatusContainer'
	| 'PatchNotes'
	| 'PostedTime'
	| 'ProgressInfoContainer'
	| 'ProgressStatus'
	| 'Separator'
	| 'Text'
	| 'TextContainer'
	| 'TimeRemaining'
	| 'Title'
	| 'TotalUpdateSize'
	| 'UnsupportedHardwareWarning'
	| 'UpdateBytesRemaining'
	| 'UpdatePanel'
	| 'UpdateScreen'
	| 'UpdateStatusContainer'
	| 'UpdaterFieldStatusApplying'
	| 'UpdaterFieldStatusSuccess'
	| 'duration-app-launch'
	| 'fadeInAnimation'
	| 'focusAnimation'
	| 'hoverAnimation',
	string
>;

type PlaySectionClasses = Record<
	| 'AchievementCountLabel'
	| 'AchievementProgressRow'
	| 'AchievementSVG'
	| 'ActionSection'
	| 'AppButtonsContainer'
	| 'Arrow'
	| 'AvatarAndPersona'
	| 'BackgroundAnimation'
	| 'BreakNarrow'
	| 'BreakShort'
	| 'BreakTall'
	| 'BreakUltraWide'
	| 'BreakWide'
	| 'ButtonChild'
	| 'ButtonText'
	| 'ChooseButton'
	| 'ClaimButton'
	| 'ClaimButtonContainer'
	| 'ClickablePlayBarItem'
	| 'CloudIconSVG'
	| 'CloudStatusIcon'
	| 'CloudStatusLabel'
	| 'CloudStatusRow'
	| 'CloudStatusSyncFail'
	| 'CloudSyncProblem'
	| 'CloudSynching'
	| 'ComingSoon'
	| 'Container'
	| 'ControllerConfigButton'
	| 'ControllerSupportInfo'
	| 'ControllerSupportRow'
	| 'DetailsProgressBar'
	| 'DetailsProgressContainer'
	| 'DetailsSection'
	| 'DetailsSectionExtra'
	| 'DetailsSectionStatus'
	| 'Disabled'
	| 'DotDotDot'
	| 'DownloadPaused'
	| 'DownloadProgressBar'
	| 'Downloading'
	| 'FavoriteButton'
	| 'Favorited'
	| 'FeatureHidden'
	| 'GameInfoButton'
	| 'GameStat'
	| 'GameStatIcon'
	| 'GameStatIconForced'
	| 'GameStatRight'
	| 'GameStatsSection'
	| 'GamepadUIBreakNarrow'
	| 'GamepadUIBreakShort'
	| 'GamepadUIBreakWide'
	| 'Glassy'
	| 'HideWhenNarrow'
	| 'Icon'
	| 'Icons'
	| 'InPage'
	| 'InnerContainer'
	| 'InvalidPlatform'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'LastPlayed'
	| 'LastPlayedInfo'
	| 'LaunchOptionCallout'
	| 'LaunchOptionCalloutMessage'
	| 'LaunchOptionCalloutMessageContainer'
	| 'LongButton'
	| 'MenuActive'
	| 'MenuButton'
	| 'MenuButtonContainer'
	| 'MiniAchievements'
	| 'OfflineMode'
	| 'OnlyDownloadBar'
	| 'PermanentlyUnavailable'
	| 'PlayBar'
	| 'PlayBarCloudStatusContainer'
	| 'PlayBarDetailLabel'
	| 'PlayBarGameIcon'
	| 'PlayBarGameName'
	| 'PlayBarIconAndGame'
	| 'PlayBarLabel'
	| 'Playtime'
	| 'PlaytimeIcon'
	| 'PlaytimeIconForced'
	| 'PortraitBar'
	| 'PrivateAppActiveIndicator'
	| 'RecentlyUpdated'
	| 'RecentlyUpdatedIcon'
	| 'RecentlyUpdatedLink'
	| 'RecentlyUpdatedText'
	| 'RightBreakNarrow'
	| 'RightBreakUltraNarrow'
	| 'RightBreakUltraWide'
	| 'RightBreakWide'
	| 'RightControls'
	| 'Row'
	| 'SharedLibrary'
	| 'ShowStreaming'
	| 'StatusAndStats'
	| 'StatusNameContainer'
	| 'StickyHeader'
	| 'StickyHeaderShadow'
	| 'SuperimposedGridItems'
	| 'SyncAnim'
	| 'Visible'
	| 'duration-app-launch'
	| 'favorited'
	| 'focusAnimation'
	| 'hoverAnimation',
	string
>;

type GamepadSliderClasses = Record<
	| 'AlignToEnds'
	| 'AlignToLeft'
	| 'AlignToRight'
	| 'BackgroundAnimation'
	| 'CompoundSlider'
	| 'CompoundSliderSubSlider'
	| 'CompoundSliderSubSliderLabel'
	| 'CompoundSliderSubSliderLabelContainer'
	| 'CompoundSliderSubSliderLabelInternal'
	| 'CompoundSliderSubSliderLabelPositioner'
	| 'DefaultValueColorLeft'
	| 'DefaultValueColorRight'
	| 'DefaultValueIsColorRange'
	| 'DefaultValueTick'
	| 'DefaultValueTickContainer'
	| 'DescriptionValue'
	| 'Disabled'
	| 'EditableValue'
	| 'ErrorShake'
	| 'FakeEditableValue'
	| 'Icon'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'LabelText'
	| 'Left'
	| 'ParenSliderHandle'
	| 'ParenSliderHandleContainer'
	| 'RedBorder'
	| 'Right'
	| 'SliderControl'
	| 'SliderControlAndNotches'
	| 'SliderControlPanelGroup'
	| 'SliderHandle'
	| 'SliderHandleContainer'
	| 'SliderHandleFocusPop'
	| 'SliderHasNotches'
	| 'SliderNotch'
	| 'SliderNotchContainer'
	| 'SliderNotchLabel'
	| 'SliderNotchTick'
	| 'SliderTrack'
	| 'SliderTrackDark'
	| 'TickActive'
	| 'VerticalLineSliderHandle'
	| 'VerticalLineSliderHandleContainer'
	| 'WithDefaultValue'
	| 'duration-app-launch'
	| 'error-shake'
	| 'error-shake-duration',
	string
>;

type AppDetailsHeaderClasses = Record<
	| 'AddBoxSizer'
	| 'Background'
	| 'Bottom'
	| 'BottomCenter'
	| 'BottomLeft'
	| 'BottomRight'
	| 'BoxSizer'
	| 'BoxSizerButtonContainer'
	| 'BoxSizerContainer'
	| 'BoxSizerDelete'
	| 'BoxSizerDragBox'
	| 'BoxSizerEdge'
	| 'BoxSizerGridBox'
	| 'BoxSizerInfo'
	| 'BoxSizerSettings'
	| 'BoxSizerValidRegion'
	| 'CenterCenter'
	| 'DialogButton'
	| 'EdgeDown'
	| 'FallbackArt'
	| 'Features'
	| 'FullscreenEnterActive'
	| 'FullscreenEnterDone'
	| 'FullscreenEnterStart'
	| 'FullscreenExitActive'
	| 'FullscreenExitDone'
	| 'FullscreenExitStart'
	| 'HeaderBackgroundImage'
	| 'ImgBlur'
	| 'ImgBlurBackdrop'
	| 'ImgContainer'
	| 'ImgSrc'
	| 'Left'
	| 'Loaded'
	| 'Middle'
	| 'NoArt'
	| 'PinBox'
	| 'Right'
	| 'SVGTitle'
	| 'SaveBoxSizer'
	| 'TextNameSpace'
	| 'TitleImageContainer'
	| 'TitleLogo'
	| 'TitleSection'
	| 'Top'
	| 'TopCapsule'
	| 'TopGradient'
	| 'TopLeft'
	| 'TopRight'
	| 'UpperCenter'
	| 'UpperLeft'
	| 'duration-app-launch',
	string
>;

type AppDetailsClasses = Record<
	| 'AppDetailsOverviewPanel'
	| 'BackgroundAnimation'
	| 'BreakNarrow'
	| 'BreakShort'
	| 'BreakTall'
	| 'BreakUltraWide'
	| 'BreakWide'
	| 'Container'
	| 'GamepadUIBreakNarrow'
	| 'GamepadUIBreakShort'
	| 'GamepadUIBreakWide'
	| 'Glassy'
	| 'Header'
	| 'HeaderLoaded'
	| 'InnerContainer'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'PlayBar'
	| 'PreventScrolling'
	| 'RightBreakNarrow'
	| 'RightBreakUltraNarrow'
	| 'RightBreakUltraWide'
	| 'RightBreakWide'
	| 'ScrollContainer'
	| 'ShowPlayBar'
	| 'Throbber'
	| 'duration-app-launch'
	| 'fadein'
	| 'focusAnimation'
	| 'hoverAnimation',
	string
>;

type GamepadUIClasses = Record<
	| 'BackgroundAnimation'
	| 'BasicHome'
	| 'BasicUiRoot'
	| 'Content'
	| 'ContinuousRenderPixel'
	| 'ContinuousRenderPixelBlink'
	| 'GamepadDialogOverlay'
	| 'GamepadUIPopupWindowBody'
	| 'HeaderHeightVisible'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'MainNavMenuAnchor'
	| 'MainNavMenuMainSplit'
	| 'OpaqueBackground'
	| 'PopupBody'
	| 'QuickAccessMenuAnchor'
	| 'StandaloneKeyboard'
	| 'SteamUIPopupHTML'
	| 'SteamUIPopupWindow'
	| 'SteamUIPopupWindowBody'
	| 'TransparentBackground'
	| 'TrueBlackBackground'
	| 'VR'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hoverAnimation'
	| 'vrgamepadui-floating-bar-popup-panel-height'
	| 'vrgamepadui-floating-bar-popup-panel-width'
	| 'vrgamepadui-floating-keyboard-height'
	| 'vrgamepadui-floating-keyboard-width'
	| 'vrgamepadui-floating-side-panel-height'
	| 'vrgamepadui-floating-side-panel-width',
	string
>;

type GamepadTabbedPageClasses = Record<
	| 'Active'
	| 'AnimateDownwardExpansion'
	| 'Arrows'
	| 'BackgroundAnimation'
	| 'BleedGlyphs'
	| 'CanBeHeaderBackground'
	| 'ContentTransition'
	| 'Enter'
	| 'EnterActive'
	| 'Exit'
	| 'ExitActive'
	| 'ExpandFadeDownwards'
	| 'FixCenterAlignScroll'
	| 'Floating'
	| 'GamepadTabbedPage'
	| 'Glyphs'
	| 'HasAddon'
	| 'IsUnderHeader'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'Left'
	| 'LeftAddon'
	| 'OverlayPinnedView'
	| 'Right'
	| 'RightAddon'
	| 'ScrolledDown'
	| 'Selected'
	| 'Show'
	| 'SortAndFilterButton'
	| 'SortAndFilterContainer'
	| 'Tab'
	| 'TabBadge'
	| 'TabContents'
	| 'TabContentsScroll'
	| 'TabCount'
	| 'TabCountBadge'
	| 'TabHeaderRowWrapper'
	| 'TabIcon'
	| 'TabRow'
	| 'TabRowSpacer'
	| 'TabRowTabs'
	| 'TabTitle'
	| 'TabsRowScroll'
	| 'contentPadding'
	| 'duration-app-launch'
	| 'headerHeight',
	string
>;

type GamepadContextMenuClasses = Record<
	| 'Arrow'
	| 'BackgroundAnimation'
	| 'BasicContextMenuContainer'
	| 'BasicContextMenuHeader'
	| 'BasicContextMenuHeaderShrinkableSpacing'
	| 'BasicContextMenuModal'
	| 'Capitalized'
	| 'ContextMenuSeparator'
	| 'Destructive'
	| 'Emphasis'
	| 'Focused'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'Label'
	| 'MenuSectionHeader'
	| 'Positive'
	| 'Selected'
	| 'SubMenu'
	| 'UpperCase'
	| 'active'
	| 'contextMenu'
	| 'contextMenuContents'
	| 'contextMenuFade'
	| 'contextMenuItem'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hasSubMenu'
	| 'hoverAnimation'
	| 'slideInAnimation',
	string
>;

type AchievementListClasses = Record<
	| 'AchievementContent'
	| 'AchievementDescription'
	| 'AchievementGlobalPercentage'
	| 'AchievementList'
	| 'AchievementListItemBase'
	| 'AchievementTitle'
	| 'AlignEnd'
	| 'Avatar'
	| 'AvatarContainer'
	| 'ComparisonAchieverColumn'
	| 'ComparisonAchieverInfo'
	| 'Container'
	| 'Content'
	| 'Description'
	| 'Footer'
	| 'FriendAchievementFooter'
	| 'GlobalAchievementListItem'
	| 'GlobalAchievementsListHeader'
	| 'GlobalPercentage'
	| 'HeaderText'
	| 'Hidden'
	| 'HiddenAchievementContent'
	| 'ImageContainer'
	| 'InBody'
	| 'Info'
	| 'ListTitle'
	| 'Percent'
	| 'ProgressBar'
	| 'ProgressContainer'
	| 'ProgressCount'
	| 'ProgressFill'
	| 'ProgressLabel'
	| 'Right'
	| 'SearchField'
	| 'Secondary'
	| 'SpoilerWarning'
	| 'Title'
	| 'Unachieved'
	| 'UnlockContainer'
	| 'UnlockDate'
	| 'UserUnlockDateTime'
	| 'VerticalContent'
	| 'duration-app-launch'
	| 'nAchievementGap'
	| 'nAchievementHeight'
	| 'nAchievementsListTitleHeight'
	| 'nGlobalAchievementHeight',
	string
>;

type AchievementPageClasses = Record<
	| 'AchievementContent'
	| 'AchievementDescription'
	| 'AchievementGlobalPercentage'
	| 'AchievementList'
	| 'AchievementListItemBase'
	| 'AchievementTabs'
	| 'AchievementTitle'
	| 'AlignEnd'
	| 'Avatar'
	| 'AvatarContainer'
	| 'Background'
	| 'Blur'
	| 'CompareButtonContainer'
	| 'ComparisonAchieverColumn'
	| 'ComparisonAchieverInfo'
	| 'Container'
	| 'Content'
	| 'Description'
	| 'DragHandle'
	| 'ErrorButtons'
	| 'ErrorContainer'
	| 'ErrorTitle'
	| 'Footer'
	| 'FriendAchievementFooter'
	| 'FriendAchievementsListHeader'
	| 'GlobalAchievementListItem'
	| 'GlobalAchievementsListHeader'
	| 'GlobalButton'
	| 'GlobalPercentage'
	| 'HeaderContainer'
	| 'HeaderImage'
	| 'HeaderText'
	| 'Hidden'
	| 'HiddenAchievementContent'
	| 'ImageContainer'
	| 'InBody'
	| 'Info'
	| 'Label'
	| 'List'
	| 'ListTitle'
	| 'LoadingContainer'
	| 'MyAchievementsHeader'
	| 'Nav'
	| 'NotOwnedMessage'
	| 'Page'
	| 'Percent'
	| 'PerfectGame'
	| 'PinnedView'
	| 'PinnedViewTabs'
	| 'ProgressBar'
	| 'ProgressContainer'
	| 'ProgressCount'
	| 'ProgressFill'
	| 'ProgressLabel'
	| 'Right'
	| 'SearchField'
	| 'Secondary'
	| 'SortableAchievementsList'
	| 'SortableUserAchievement'
	| 'SortableUserAchievementInner'
	| 'SpoilerWarning'
	| 'Text'
	| 'Throbber'
	| 'Title'
	| 'ToggleContainer'
	| 'Unachieved'
	| 'UnlockContainer'
	| 'UnlockDate'
	| 'UserContext'
	| 'UserUnlockDateTime'
	| 'VerticalContent'
	| 'duration-app-launch'
	| 'headerPadding'
	| 'nAchievementGap'
	| 'nAchievementHeight'
	| 'nAchievementsListTitleHeight'
	| 'nGlobalAchievementHeight',
	string
>;

type MainMenuAppRunningClasses = Record<
	| 'Active'
	| 'ActiveContent'
	| 'ActiveDot'
	| 'AppColumn'
	| 'AppColumnContent'
	| 'AppRunningControls'
	| 'BackgroundAnimation'
	| 'Collapsible'
	| 'Container'
	| 'ControllerColumnFocused'
	| 'CurrentGameBackground'
	| 'CurrentGameLogo'
	| 'Disabled'
	| 'FocusedColumn'
	| 'HideMask'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'KeyBoardVisible'
	| 'NavColumnFocused'
	| 'NavigationBox'
	| 'NavigationColumn'
	| 'NavigationMenuItem'
	| 'NavigationMenuItemSeparator'
	| 'OverlayAchievements'
	| 'OverlayGuides'
	| 'OverlayInplaceBrowser'
	| 'OverlayNotes'
	| 'ScrollMask'
	| 'SelectableAppWindow'
	| 'SwitchAppsTitle'
	| 'Visible'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hoverAnimation',
	string
>;

type BasicAppDetailsSectionStylerClasses = Record<
	| 'ActionButtonAndStatusPanel'
	| 'ActionRow'
	| 'AppActionButton'
	| 'AppButtons'
	| 'AppDetailSectionList'
	| 'AppDetailsContainer'
	| 'AppDetailsContent'
	| 'AppDetailsRoot'
	| 'CollectionsHeader'
	| 'DeckVerifiedFeedbackButton'
	| 'DeckVerifiedFeedbackConfirmation'
	| 'DeckVerifiedFeedbackConfirmationContainer'
	| 'DeckVerifiedFeedbackContainer'
	| 'DeckVerifiedFeedbackQuestion'
	| 'GameInfoCollections'
	| 'GameInfoContainer'
	| 'GameInfoQuickLinks'
	| 'Header'
	| 'InvertFocusedIcon'
	| 'PlaySection'
	| 'duration-app-launch'
	| 'headerPadding',
	string
>;

type SteamSpinnerClasses = Record<
	| 'BackgroundAnimation'
	| 'Black'
	| 'Container'
	| 'ContainerBackground'
	| 'ExtraSpace'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'LoadingStatus'
	| 'Medium'
	| 'Small'
	| 'Spacer'
	| 'SpinnerLoaderContainer'
	| 'focusAnimation'
	| 'hoverAnimation',
	string
>;

type FooterClasses = Record<
	| 'BackgroundAnimation'
	| 'BasicFooter'
	| 'FooterLegend'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'Opaque'
	| 'PillShapedIcon'
	| 'QuickAccessFooter'
	| 'Relative'
	| 'Spacer'
	| 'WithKeyboard'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hoverAnimation',
	string
>;

type AppActionButtonClasses = Record<
	| 'BackgroundAnimation'
	| 'BreakNarrow'
	| 'BreakShort'
	| 'BreakTall'
	| 'BreakUltraWide'
	| 'BreakWide'
	| 'ButtonChild'
	| 'ButtonText'
	| 'ButtonThrobberPadding'
	| 'Disabled'
	| 'ForceShutdownButton'
	| 'GamepadUIBreakNarrow'
	| 'GamepadUIBreakShort'
	| 'GamepadUIBreakWide'
	| 'Green'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'LongButton'
	| 'NoAction'
	| 'PlayButton'
	| 'PlayButtonContainer'
	| 'RightBreakNarrow'
	| 'RightBreakUltraNarrow'
	| 'RightBreakUltraWide'
	| 'RightBreakWide'
	| 'ShowStreaming'
	| 'ShowingStreaming'
	| 'ShutdownAppButton'
	| 'StreamingCallout'
	| 'StreamingCalloutMessage'
	| 'StreamingCalloutMessageContainer'
	| 'StreamingContextMenuItem'
	| 'StreamingSelector'
	| 'Throbber'
	| 'ThrobberContainer'
	| 'WaitingForForceShutdown'
	| 'WaitingForShutdownSpinner'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hoverAnimation'
	| 'rotate',
	string
>;

type LibraryAssetImageClasses = Record<
	| 'Container'
	| 'GreyBackground'
	| 'Hidden'
	| 'Image'
	| 'LandscapeImage'
	| 'LongTitles'
	| 'NoTransitions'
	| 'PortraitImage'
	| 'Short'
	| 'Title'
	| 'Visibility'
	| 'Visible'
	| 'duration-app-launch',
	string
>;

type GamepadLibraryClasses = Record<
	| 'AppGridFilterHeader'
	| 'AppGridFilterHeaderAsButton'
	| 'AppGridFilterText'
	| 'BackgroundAnimation'
	| 'BreakNarrow'
	| 'BreakShort'
	| 'BreakTall'
	| 'BreakUltraWide'
	| 'BreakWide'
	| 'CollectionContents'
	| 'CollectionHeader'
	| 'ComingSoon'
	| 'GamepadLibrary'
	| 'GamepadUIBreakNarrow'
	| 'GamepadUIBreakShort'
	| 'GamepadUIBreakWide'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'RightBreakNarrow'
	| 'RightBreakUltraNarrow'
	| 'RightBreakUltraWide'
	| 'RightBreakWide'
	| 'duration-app-launch'
	| 'focusAnimation'
	| 'hoverAnimation',
	string
>;

type FocusRingClasses = Record<'DebugFocusRing' | 'FocusRing' | 'FocusRingOnHiddenItem' | 'FocusRingRoot' | 'blinker' | 'fadeOutline' | 'flash' | 'growOutline', string>;

type SearchBarClasses = Record<
	| 'BackgroundAnimation'
	| 'ForceExpanded'
	| 'IconMovesOnHover'
	| 'ItemFocusAnim-darkGrey'
	| 'ItemFocusAnim-darkerGrey'
	| 'ItemFocusAnim-darkerGrey-nocolor'
	| 'ItemFocusAnim-green'
	| 'ItemFocusAnim-grey'
	| 'ItemFocusAnim-translucent-white-10'
	| 'ItemFocusAnim-translucent-white-20'
	| 'ItemFocusAnimBorder-darkGrey'
	| 'SearchAndTitleContainer'
	| 'SearchBox'
	| 'SearchFieldBackground'
	| 'SearchIconLeft'
	| 'SearchIconRight'
	| 'ShowingSearch'
	| 'ShowingTitle'
	| 'VR'
	| 'Visible'
	| 'WhiteBackground'
	| 'duration-app-launch',
	string
>;

type MainBrowserClasses = Record<
	| 'Browser'
	| 'BrowserContainer'
	| 'BrowserNavRoot'
	| 'Disabled'
	| 'ExternalBrowserContainer'
	| 'InputSupportLevel'
	| 'MainBrowser'
	| 'MainBrowserContainer'
	| 'MicroTxnContainer'
	| 'NavigationButton'
	| 'RequireTouchscreenLabel'
	| 'StatusIcon'
	| 'Toggled'
	| 'URL'
	| 'URLBar'
	| 'URLInput'
	| 'Visible'
	| 'duration-app-launch'
	| 'showSupportLevel',
	string
>;

/** @component Static Classes */
export const quickAccessMenuClasses = findClassModule((m) => m.Title && m.QuickAccessMenu && m.BatteryDetailsLabels) as QuickAccessMenuClasses;
/** @component Static Classes */
export const scrollPanelClasses = findClassModule((m) => m.ScrollPanel) as ScrollPanelClasses;
/** @component Static Classes */
export const gamepadDialogClasses = findClassModule((m) => m.GamepadDialogContent && !m.BindingButtons) as GamepadDialogClasses;
/** @component Static Classes */
export const quickAccessControlsClasses = findClassModule(
	(m) => m.BatteryPercentageLabel && m.PanelSection && !m['vr-dashboard-bar-height'] && !m.QuickAccessMenu && !m.QuickAccess && !m.PerfProfileInfo,
) as QuickAccessControlsClasses;
/** @component Static Classes */
export const updaterFieldClasses = findClassModule((m) => m.OOBEUpdateStatusContainer) as UpdaterFieldClasses;
/** @component Static Classes */
export const playSectionClasses = findClassModule((m) => m.PlayBarDetailLabel) as PlaySectionClasses;
/** @component Static Classes */
export const gamepadSliderClasses = findClassModule((m) => m.SliderControlPanelGroup) as GamepadSliderClasses;
/** @component Static Classes */
export const appDetailsHeaderClasses = findClassModule((m) => m.TopCapsule) as AppDetailsHeaderClasses;
/** @component Static Classes */
export const appDetailsClasses = findClassModule((m) => m.HeaderLoaded) as AppDetailsClasses;
/** @component Static Classes */
export const gamepadUIClasses = findClassModule((m) => m.BasicUiRoot) as GamepadUIClasses;
/** @component Static Classes */
export const gamepadTabbedPageClasses = findClassModule((m) => m.GamepadTabbedPage) as GamepadTabbedPageClasses;
/** @component Static Classes */
export const gamepadContextMenuClasses = findClassModule((m) => m.BasicContextMenuModal) as GamepadContextMenuClasses;
/** @component Static Classes */
export const achievementListClasses = findClassModule((m) => m.AchievementListItemBase && !m.Page) as AchievementListClasses;
/** @component Static Classes */
export const achievementPageClasses = findClassModule((m) => m.AchievementListItemBase && m.Page) as AchievementPageClasses;
/** @component Static Classes */
export const mainMenuAppRunningClasses = findClassModule((m) => m.AppRunningControls && m.OverlayAchievements) as MainMenuAppRunningClasses;
/** @component Static Classes */
export const basicAppDetailsSectionStylerClasses = findClassModule((m) => m.AppDetailsRoot) as BasicAppDetailsSectionStylerClasses;
/** @component Static Classes */
export const steamSpinnerClasses = findClassModule((m) => m.SpinnerLoaderContainer) as SteamSpinnerClasses;
/** @component Static Classes */
export const footerClasses = findClassModule((m) => m.QuickAccessFooter) as FooterClasses;
/** @component Static Classes */
export const appActionButtonClasses = findClassModule((m) => m.PlayButtonContainer) as AppActionButtonClasses;
/** @component Static Classes */
export const libraryAssetImageClasses = findClassModule((m) => m.LongTitles && m.GreyBackground) as LibraryAssetImageClasses;
/** @component Static Classes */
export const gamepadLibraryClasses = findClassModule((m) => m.GamepadLibrary) as GamepadLibraryClasses;
/** @component Static Classes */
export const focusRingClasses = findClassModule((m) => m.FocusRingRoot) as FocusRingClasses;
/** @component Static Classes */
export const searchBarClasses = findClassModule((m) => m.SearchAndTitleContainer) as SearchBarClasses;
/** @component Static Classes */
export const mainBrowserClasses = findClassModule((m) => m.MainBrowserContainer) as MainBrowserClasses;

/**
 * @component Static Classes
 * @deprecated please use quickAccessMenuClasses instead
 */
export const staticClasses = quickAccessMenuClasses;

/**
 * @component Static Classes
 * @deprecated please use scrollPanelClasses instead
 */
export const scrollClasses = scrollPanelClasses;

/**
 * @component Static Classes
 * @deprecated please use achievementListClasses instead
 */
export const achievementClasses = achievementListClasses;
