name: Build Millennium

on:
  workflow_dispatch:
    inputs:
      release_artifacts:
        description: "Release build?"
        required: true
        default: "no"

concurrency:
  group: ci-build
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Download Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Download Semantic Release
        run: |
          npm install -g pnpm
          pnpm install --save-dev semantic-release @semantic-release/github @semantic-release/exec @semantic-release/changelog @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Next Version
        id: get_version
        run: |
          cd scripts && npx semantic-release --dry-run --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: prepare
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update Millennium Version
        if: ${{ needs.prepare.outputs.version != '' }}
        run: |
          echo "# current version of millennium" > ./scripts/version
          echo "v${{ needs.prepare.outputs.version }}" >> ./scripts/version

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build Millennium Backend
        shell: pwsh
        run: |
          $vsDevCmd = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"

          cmd /c "`"$vsDevCmd`" -arch=x64 -host_arch=x64 & set" |
          Where-Object { $_ -match '=' } |
          ForEach-Object {
              $k,$v = $_ -split '=',2
              Set-Item "env:$k" $v
          }

          cd src/typescript
          bun install
          cd ttc && bun run build && cd ..
          bun install
          bun run build
          cd ../..

          cmake --preset=windows-release -DGITHUB_ACTION_BUILD=ON
          cmake --build build

          New-Item -ItemType Directory -Force -Path D:/a/millennium-build/lib
          New-Item -ItemType Directory -Force -Path D:/a/millennium-build/bin
          Copy-Item ./build/millennium.dll               D:/a/millennium-build/lib/millennium.dll
          Copy-Item ./build/millennium.bootstrap64.dll    D:/a/millennium-build/lib/millennium.bootstrap64.dll
          Copy-Item ./build/millennium.hhx64.dll         D:/a/millennium-build/lib/millennium.hhx64.dll
          Copy-Item ./build/millennium.luasb64.exe        D:/a/millennium-build/bin/millennium.luasb64.exe
          Copy-Item ./build/millennium.crashhandler64.exe D:/a/millennium-build/bin/millennium.crashhandler64.exe

          # Collect PDB files for debug symbols
          New-Item -ItemType Directory -Force -Path D:/a/pdb
          Get-ChildItem -Path ./build -Recurse -Filter *.pdb | Copy-Item -Destination D:/a/pdb/

      - name: Upload Unsigned Build Artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: unsigned-millennium-windows
          path: D:/a/millennium-build/

      - name: Upload PDB Symbols
        uses: actions/upload-artifact@v4
        with:
          name: millennium-pdb
          path: D:/a/pdb/

      - name: Sign Millennium Build
        id: sign_artifact
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: "${{ secrets.SIGNPATH_API_TOKEN }}"
          organization-id: "f90532fc-e58c-4863-bc0d-72623720335f"
          project-slug: "Millennium"
          signing-policy-slug: "release-signing"
          artifact-configuration-slug: "wsock32-hook"
          github-artifact-id: "${{ steps.upload-unsigned-artifact.outputs.artifact-id }}"
          output-artifact-directory: "signed-millennium"
          wait-for-completion: true

      - name: Upload Signed Build Release
        id: upload-signed-artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: signed-millennium-windows
          path: D:\a\Millennium\Millennium\signed-millennium

  build-linux:
    needs: prepare
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update Millennium Version
        if: ${{ needs.prepare.outputs.version != '' }}
        run: |
          echo "# current version of millennium" > ./scripts/version
          echo "v${{ needs.prepare.outputs.version }}" >> ./scripts/version

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib g++-multilib libc6-dev-i386 libgtk-3-dev ninja-build libpsl-dev:i386 libssl-dev:i386 pkg-config:i386

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.28"

      - name: Build Millennium Backend
        run: |
          export PKG_CONFIG_PATH="/usr/lib/i386-linux-gnu/pkgconfig:/usr/lib/pkgconfig"
          export CMAKE_LIBRARY_PATH="/usr/lib/i386-linux-gnu"
          export CMAKE_INCLUDE_PATH="/usr/include/i386-linux-gnu"
          export PKG_CONFIG_LIBDIR="/usr/lib/i386-linux-gnu/pkgconfig"

          cd src/typescript
          bun install
          cd ttc && bun run build && cd ..
          bun install
          bun run build
          cd ../..

          cmake --preset=linux-release -G "Ninja" -DGITHUB_ACTION_BUILD=ON \
            -DCMAKE_LIBRARY_PATH="/usr/lib/i386-linux-gnu" \
            -DCMAKE_INCLUDE_PATH="/usr/include" \
            -DCMAKE_FIND_ROOT_PATH="/usr/lib/i386-linux-gnu" \
            -DCMAKE_PREFIX_PATH="/usr/lib/i386-linux-gnu" \
            -DCMAKE_SYSTEM_LIBRARY_PATH="/usr/lib/i386-linux-gnu" \
            -DPKG_CONFIG_EXECUTABLE="/usr/bin/pkg-config" \
            -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=ON

          # Build the project
          cmake --build build --config Release -- -j$(nproc)

          # Create final directory structure
          mkdir -p ~/build/usr/lib/millennium

          # Copy binaries and libraries directly to final locations
          cp build/libmillennium_x86.so ~/build/usr/lib/millennium/
          cp build/libmillennium_bootstrap_86x.so ~/build/usr/lib/millennium/
          cp build/libmillennium_hhx64.so ~/build/usr/lib/millennium/
          cp build/millennium_luasb86 ~/build/usr/lib/millennium/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: millennium-linux
          path: ~/build/

  release:
    needs: [prepare, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: ${{ inputs.release_artifacts == 'yes' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Download Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Semantic Release
        run: npm install --save-dev semantic-release @semantic-release/github @semantic-release/exec @semantic-release/changelog @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: signed-millennium-windows
          path: ./artifacts/windows

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: millennium-linux
          path: ./artifacts/linux

      - name: Download PDB Symbols
        uses: actions/download-artifact@v4
        with:
          name: millennium-pdb
          path: ./artifacts/pdb

      - name: Update Millennium Version
        if: ${{ needs.prepare.outputs.version != '' }}
        run: |
          echo "# current version of millennium" > ./scripts/version
          echo "v${{ needs.prepare.outputs.version }}" >> ./scripts/version

      - name: Release Millennium
        run: |
          mkdir -p ./artifacts/release

          linux_release_name="./artifacts/release/millennium-v${{ needs.prepare.outputs.version }}-linux-x86_64"
          win32_name="millennium-v${{ needs.prepare.outputs.version }}-windows-x86_64"
          win32_release_name="./artifacts/release/${win32_name}"

          # setup windows release
          cd ./artifacts/windows && zip -r ../release/${win32_name}.zip . && cd ../..
          sha256sum ${win32_release_name}.zip > ${win32_release_name}.sha256
          sed -i 's#\./artifacts/release/##g' ${win32_release_name}.sha256
          du -sb ./artifacts/windows | awk '{print $1}' > ${win32_release_name}.installsize

          # setup linux release
          tar -czvf ${linux_release_name}.tar.gz -C ./artifacts/linux .
          sha256sum ${linux_release_name}.tar.gz > ${linux_release_name}.sha256
          sed -i 's#\./artifacts/release/##g' ${linux_release_name}.sha256
          du -sb ./artifacts/linux | awk '{print $1}' > ${linux_release_name}.installsize

          # setup PDB symbols release
          pdb_name="millennium-v${{ needs.prepare.outputs.version }}-pdb"
          pdb_release_name="./artifacts/release/${pdb_name}"
          cd ./artifacts/pdb && zip -r ../release/${pdb_name}.zip . && cd ../..
          sha256sum ${pdb_release_name}.zip > ${pdb_release_name}.sha256
          sed -i 's#\./artifacts/release/##g' ${pdb_release_name}.sha256

          cd scripts && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
