/**
 * Auto-generated by Millennium during CMake configuration - do not edit manually :)
 */
#define INCBIN_PREFIX
#include "incbin.h"
/** Millennium frontend library -- responsible for displaying Millennium UI, and loading themes */
INCTXT(MILLENNIUM_FRONTEND_BIN_, "../../../assets/.millennium/Dist/index.js");

/** Millennium API library */
INCTXT(MILLENNIUM_API_BIN_, "../../../sdk/typescript-packages/loader/build/millennium.js");
/** Millennium API chunk files */
INCTXT(MILLENNIUM_CHUNK_BROWSER_INIT_BIN_, "../../../sdk/typescript-packages/loader/build/chunks/chunk-browser-init.js");
INCTXT(MILLENNIUM_CHUNK_INDEX_BIN_, "../../../sdk/typescript-packages/loader/build/chunks/chunk-index.js");
INCTXT(MILLENNIUM_CHUNK_LOGGER_BIN_, "../../../sdk/typescript-packages/loader/build/chunks/chunk-logger.js");
INCTXT(MILLENNIUM_CHUNK_MILLENNIUM_API_BIN_, "../../../sdk/typescript-packages/loader/build/chunks/chunk-millennium-api.js");
INCTXT(MILLENNIUM_CHUNK_WEBPACK_BIN_, "../../../sdk/typescript-packages/loader/build/chunks/chunk-webpack.js");

// clang-format off
std::unordered_map<std::string, const char*> INTERNAL_FTP_CALL_DATA = {
	{ fmt::format("https://millennium.ftp/{}/millennium-frontend.js", GetScrambledApiPathToken()), MILLENNIUM_FRONTEND_BIN_Data },
	{ fmt::format("https://millennium.ftp/{}/millennium.js", GetScrambledApiPathToken()), MILLENNIUM_API_BIN_Data },
	{ fmt::format("https://millennium.ftp/{}/chunks/chunk-browser-init.js", GetScrambledApiPathToken()), MILLENNIUM_CHUNK_BROWSER_INIT_BIN_Data },
	{ fmt::format("https://millennium.ftp/{}/chunks/chunk-index.js", GetScrambledApiPathToken()), MILLENNIUM_CHUNK_INDEX_BIN_Data },
	{ fmt::format("https://millennium.ftp/{}/chunks/chunk-logger.js", GetScrambledApiPathToken()), MILLENNIUM_CHUNK_LOGGER_BIN_Data },
	{ fmt::format("https://millennium.ftp/{}/chunks/chunk-millennium-api.js", GetScrambledApiPathToken()), MILLENNIUM_CHUNK_MILLENNIUM_API_BIN_Data },
	{ fmt::format("https://millennium.ftp/{}/chunks/chunk-webpack.js", GetScrambledApiPathToken()), MILLENNIUM_CHUNK_WEBPACK_BIN_Data }
};
// clang-format on
